services:
  laravel-filepond-13:
    image: laravel-filepond-13-development:13.x
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
    container_name: laravel-filepond-13-dev
    stdin_open: true
    tty: true
    volumes:
      - '.:/code'
    network_mode: host
